# Generated by Django 5.2.1 on 2025-05-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField()),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_rented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_years', models.IntegerField()),
                ('start_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to='properties.property')),
            ],
        ),
    ]
